In [67]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import os
from datetime import datetime

Ouverture du fichier pour la corespondance des noms de colonne

In [68]:
columns_identifier = pd.read_csv('data/columns_identifier.csv', sep=';', encoding="latin1")

columns_identifier["parameter_description_fr"] = columns_identifier["parameter_description_fr"].replace(to_replace=r';', value='/', regex=True)

dict_nameColumns = dict(zip(columns_identifier["parameter_shortname"], columns_identifier["parameter_description_fr"]))

columns_identifier.head()

,parameter_shortname,parameter_description_de,parameter_description_fr,parameter_description_it,parameter_description_en,parameter_group_de,parameter_group_fr,parameter_group_it,parameter_group_en,parameter_granularity,parameter_decimals,parameter_datatype,parameter_unit
0,dkl010d0,Windrichtung; Tagesmittel,Direction du vent/ moyenne journalière,Direzione del vento; media giornaliera,Wind direction; daily mean,Wind,vent,vento,wind,D,0,Integer,°
1,dkl010h0,Windrichtung; Stundenmittel,Direction du vent/ moyenne horaire,Direzione del vento; media oraria,Wind direction; hourly mean,Wind,vent,vento,wind,H,0,Integer,°
2,dkl010z0,Windrichtung; Zehnminutenmittel,Direction du vent/ moyenne sur 10 minutes,Direzione del vento; media su 10',Wind direction; ten minutes mean,Wind,vent,vento,wind,T,0,Integer,°
3,erefaod0,Referenzverdunstung nach FAO; Tagessumme,Évaporation de réference de FAO/ somme journal...,Evaporazione referenze di FAO; somma giornaliera,Reference evaporation from FAO; daily total,Verdunstung,évaporation,evaporazione,evaporation,D,1,Float,mm/d
4,erefaoh0,Referenzverdunstung nach FAO; Stundensumme,Évaporation de réference de FAO/ somme horaire,Evaporazione referenze di FAO; somma oraria,Reference evaporation from FAO; hourly total,Verdunstung,évaporation,evaporazione,evaporation,H,3,Float,mm/h

Ouverture du fichier d'itentification des stations

In [69]:
station_identifier = pd.read_csv('data/station_identifier.csv', sep=';', encoding="latin1")

dict_nameContry = dict(zip(station_identifier["station_abbr"], station_identifier["station_name"]))

station_identifier.head()

,station_abbr,station_name,station_canton,station_wigos_id,station_type_de,station_type_fr,station_type_it,station_type_en,station_dataowner,station_data_since,...,station_coordinates_wgs84_lat,station_coordinates_wgs84_lon,station_exposition_de,station_exposition_fr,station_exposition_it,station_exposition_en,station_url_de,station_url_fr,station_url_it,station_url_en
0,ABO,Adelboden,BE,0-20000-0-06735,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,"MeteoSchweiz, SLF",01.01.1901,...,46.491703,7.560703,Südosthang,Versant sud-est,Versante sud-orientale,south-eastern oriented slope,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
1,AEG,Oberägeri,ZG,0-20000-0-06676,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.02.1993,...,47.133636,8.608206,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
2,AIG,Aigle,VD,0-20000-0-06712,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.01.1961,...,46.326647,6.924472,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
3,ALT,Altdorf,UR,0-20000-0-06672,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.01.1864,...,46.887069,8.621894,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
4,AND,Andeer,GR,0-20000-0-06787,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.01.1901,...,46.610139,9.431981,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...

Classer les stations en fonction de leur altitude pas 500 mètres

In [70]:
#station_500 = station_identifier[(station_identifier['station_height_masl'] > 0) & (station_identifier['station_height_masl'] <= 500)].sort_values(by='station_height_masl')
#station_500_1000 = station_identifier[(station_identifier['station_height_masl'] > 500) & (station_identifier['station_height_masl'] <= 1000)].sort_values(by='station_height_masl')
#station_1000_1500 = station_identifier[(station_identifier['station_height_masl'] > 1000) & (station_identifier['station_height_masl'] <= 1500)].sort_values(by='station_height_masl')
station_1500_2000 = station_identifier[(station_identifier['station_height_masl'] > 1500) & (station_identifier['station_height_masl'] <= 2000)].sort_values(by='station_height_masl')
station_2000_2500 = station_identifier[(station_identifier['station_height_masl'] > 2000) & (station_identifier['station_height_masl'] <= 2500)].sort_values(by='station_height_masl')
station_2500_3000 = station_identifier[(station_identifier['station_height_masl'] > 2500) & (station_identifier['station_height_masl'] <= 3000)].sort_values(by='station_height_masl')
station_3000_3500 = station_identifier[(station_identifier['station_height_masl'] > 3000) & (station_identifier['station_height_masl'] <= 3500)].sort_values(by='station_height_masl')
station_3500_4000 = station_identifier[(station_identifier['station_height_masl'] > 3500) & (station_identifier['station_height_masl'] <= 4000)].sort_values(by='station_height_masl')

Function qui enregistre les données en fontion de l'altitude de la station

In [71]:
def stationHeigth(staion_abbr, name_file):
    df_list = []
    current_directory = os.getcwd()

    OUTPUT_CSV = "\\data\\" + name_file

    folder_path = current_directory + "\\data\\dataTemp\\month"
    csv_files = os.listdir(folder_path)

    for file in csv_files:
        try:
            file_path = folder_path + '\\' + file
            # Get the file size in kbytes
            file_size = os.path.getsize(file_path) / 1024

            if file_size > 1000:
                if (file.split('.')[0].upper() in staion_abbr):
                    df = pd.read_csv(folder_path + '\\' + file)
                    df_list.append(df)

        except Exception as e:
            print(f"⚠️ Erreur de lecture {file} : {e}")
    
    # Concaténation avec gestion des colonnes manquantes
    if df_list:
        df_final = pd.concat(df_list, ignore_index=True, sort=False)
        df_final.to_csv(current_directory + OUTPUT_CSV, index=False)
        print(f"✅ Fichier final enregistré sous {OUTPUT_CSV}")

Crée les fichier de données

In [72]:
#stationHeigth(list(station_500['station_abbr']), "dataWeather_500.csv")
#stationHeigth(list(station_500_1000['station_abbr']), "dataWeather_500_1000.csv")
#stationHeigth(list(station_1000_1500['station_abbr']), "dataWeather_1000_1500.csv")
stationHeigth(list(station_1500_2000['station_abbr']), "dataWeather_1500_2000.csv")
stationHeigth(list(station_2000_2500['station_abbr']), "dataWeather_2000_2500.csv")
stationHeigth(list(station_2500_3000['station_abbr']), "dataWeather_2500_3000.csv")
stationHeigth(list(station_3000_3500['station_abbr']), "dataWeather_3000_3500.csv")
stationHeigth(list(station_3500_4000['station_abbr']), "dataWeather_3500_4000.csv")

✅ Fichier final enregistré sous \data\dataWeather_1500_2000.csv
✅ Fichier final enregistré sous \data\dataWeather_2000_2500.csv
✅ Fichier final enregistré sous \data\dataWeather_2500_3000.csv
✅ Fichier final enregistré sous \data\dataWeather_3000_3500.csv
✅ Fichier final enregistré sous \data\dataWeather_3500_4000.csv

Ouvre le fichier de donnée sur les satations par altitude

In [73]:
#dataWeather_500 =  pd.read_csv('data/dataWeather_500.csv', sep=';')
#dataWeather_500_1000 =  pd.read_csv('data/dataWeather_500_1000.csv', sep=';')
#dataWeather_1000_1500 =  pd.read_csv('data/dataWeather_1000_1500.csv', sep=';')

dataWeather_1500_2000 =  pd.read_csv('data/dataWeather_1500_2000.csv', sep=';')
dataWeather_2000_2500 =  pd.read_csv('data/dataWeather_2000_2500.csv', sep=';')
dataWeather_2500_3000 =  pd.read_csv('data/dataWeather_2500_3000.csv', sep=';')
dataWeather_3000_3500 =  pd.read_csv('data/dataWeather_3000_3500.csv', sep=';')
dataWeather_3500_4000 =  pd.read_csv('data/dataWeather_3500_4000.csv', sep=';')


#print(f"Station jusuq'à 500 mètres. Dimension des données: {dataWeather_500.shape}")
#print(f"Station de plus de 500 mètres à 1000 mètres. Dimension des données: {dataWeather_500_1000.shape}")
#print(f"Station de plus de 1000 mètres à 1500 mètres. Dimension des données: {dataWeather_1000_1500.shape}")

print(f"Station de plus de 1500 mètres à 2000 mètres. Dimension des données: {dataWeather_1500_2000.shape}")
print(f"Station de plus de 2000 mètres à 2500 mètres. Dimension des données: {dataWeather_2000_2500.shape}")
print(f"Station de plus de 2500 mètres à 3000 mètres. Dimension des données: {dataWeather_2500_3000.shape}")
print(f"Station de plus de 3000 mètres à 3500 mètres. Dimension des données: {dataWeather_3000_3500.shape}")
print(f"Station de plus de 3500 mètres à 4000 mètres. Dimension des données: {dataWeather_3500_4000.shape}")

Station de plus de 1500 mètres à 2000 mètres. Dimension des données: (562004, 37)
Station de plus de 2000 mètres à 2500 mètres. Dimension des données: (177109, 37)
Station de plus de 2500 mètres à 3000 mètres. Dimension des données: (120150, 37)
Station de plus de 3000 mètres à 3500 mètres. Dimension des données: (39297, 37)
Station de plus de 3500 mètres à 4000 mètres. Dimension des données: (33603, 37)

Change le format de la date

In [74]:
#dataWeather_500['reference_timestamp'] = pd.to_datetime(dataWeather_500['reference_timestamp'], format='%d.%m.%Y %H:%M')
#dataWeather_500_1000['reference_timestamp'] = pd.to_datetime(dataWeather_500_1000['reference_timestamp'], format='%d.%m.%Y %H:%M')
#dataWeather_1000_1500['reference_timestamp'] = pd.to_datetime(dataWeather_1000_1500['reference_timestamp'], format='%d.%m.%Y %H:%M')

dataWeather_1500_2000['reference_timestamp'] = pd.to_datetime(dataWeather_1500_2000['reference_timestamp'], format='%d.%m.%Y %H:%M')
dataWeather_2000_2500['reference_timestamp'] = pd.to_datetime(dataWeather_2000_2500['reference_timestamp'], format='%d.%m.%Y %H:%M')
dataWeather_2500_3000['reference_timestamp'] = pd.to_datetime(dataWeather_2500_3000['reference_timestamp'], format='%d.%m.%Y %H:%M')
dataWeather_3000_3500['reference_timestamp'] = pd.to_datetime(dataWeather_3000_3500['reference_timestamp'], format='%d.%m.%Y %H:%M')
dataWeather_3500_4000['reference_timestamp'] = pd.to_datetime(dataWeather_3500_4000['reference_timestamp'], format='%d.%m.%Y %H:%M')

Supprime les lignes en dessous de 1960

In [75]:
year_selected = 1960

#dataWeather_500 = dataWeather_500[dataWeather_500['reference_timestamp'].dt.year >= year_selected]
#dataWeather_500_1000 = dataWeather_500_1000[dataWeather_500_1000['reference_timestamp'].dt.year >= year_selected]
#dataWeather_1000_1500 = dataWeather_1000_1500[dataWeather_1000_1500['reference_timestamp'].dt.year >= year_selected]
dataWeather_1500_2000 = dataWeather_1500_2000[dataWeather_1500_2000['reference_timestamp'].dt.year >= year_selected]
dataWeather_2000_2500 = dataWeather_2000_2500[dataWeather_2000_2500['reference_timestamp'].dt.year >= year_selected]
dataWeather_2500_3000 = dataWeather_2500_3000[dataWeather_2500_3000['reference_timestamp'].dt.year >= year_selected]
dataWeather_3000_3500 = dataWeather_3000_3500[dataWeather_3000_3500['reference_timestamp'].dt.year >= year_selected]
dataWeather_3500_4000 = dataWeather_3500_4000[dataWeather_3500_4000['reference_timestamp'].dt.year >= year_selected]

####   Column selectionnée                                                                               

 <div style="vertical-align: middle;">
    <p>station_abbr</p>
    <p>station_height_masl</p>          
    <p>reference_timestamp</p>
    <p>Température de l'air à 2 m du sol/ moyenne journalière [tre200d0]</p>
    <p>Vitesse du vent scalaire/ moyenne journalière en m/s [fkl010d0]</p>                         
    <p> Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant  [rre150d0]</p>
    <p>Hauteur de neige (mesurée automatiquement) / mesure matinale de 6 UTC [htoautd0]</p>
</div>

In [76]:
columns_list = ['station_abbr','reference_timestamp','tre200d0','fkl010d0','rre150d0', 'htoautd0']

complete_list = list(columns_identifier['parameter_shortname'])

column_names = dataWeather_1500_2000.columns.tolist()

dif_list = list(set(column_names) ^ set(columns_list))

#dataWeather_500 = dataWeather_500.drop(columns=dif_list, axis=1)
#dataWeather_500_1000 = dataWeather_500_1000.drop(columns=dif_list, axis=1)
#dataWeather_1000_1500 = dataWeather_1000_1500.drop(columns=dif_list, axis=1)

dataWeather_1500_2000 = dataWeather_1500_2000.drop(columns=dif_list, axis=1)
dataWeather_2000_2500 = dataWeather_2000_2500.drop(columns=dif_list, axis=1)
dataWeather_2500_3000 = dataWeather_2500_3000.drop(columns=dif_list, axis=1)
dataWeather_3000_3500 = dataWeather_3000_3500.drop(columns=dif_list, axis=1)
dataWeather_3500_4000 = dataWeather_3500_4000.drop(columns=dif_list, axis=1)

Modifie le nom des colonnes et le nom des villes

In [77]:
dataWeather_1500_2000_name = dataWeather_1500_2000.copy()
dataWeather_2000_2500_name = dataWeather_2000_2500.copy()
dataWeather_2500_3000_name = dataWeather_2500_3000.copy()
dataWeather_3000_3500_name = dataWeather_3000_3500.copy()
dataWeather_3500_4000_name = dataWeather_3500_4000.copy()

dataWeather_1500_2000_name['station_abbr'] = dataWeather_1500_2000['station_abbr'].map(dict_nameContry)
dataWeather_2000_2500_name['station_abbr'] = dataWeather_2000_2500['station_abbr'].map(dict_nameContry)
dataWeather_2500_3000_name['station_abbr'] = dataWeather_2500_3000['station_abbr'].map(dict_nameContry)
dataWeather_3000_3500_name['station_abbr'] = dataWeather_3000_3500['station_abbr'].map(dict_nameContry)
dataWeather_3500_4000_name['station_abbr'] = dataWeather_3500_4000['station_abbr'].map(dict_nameContry)

dataWeather_1500_2000_name.rename(dict_nameColumns, axis=1, inplace=True)
dataWeather_2000_2500_name.rename(dict_nameColumns, axis=1, inplace=True)
dataWeather_2500_3000_name.rename(dict_nameColumns, axis=1, inplace=True)
dataWeather_3000_3500_name.rename(dict_nameColumns, axis=1, inplace=True)
dataWeather_3500_4000_name.rename(dict_nameColumns, axis=1, inplace=True)

Information sur la base de donnée 1500 mètres à 2000 mètres

In [78]:
dataWeather_1500_2000_name.info()
dataWeather_1500_2000_name.head()

<class 'pandas.core.frame.DataFrame'>
Index: 361674 entries, 21914 to 562003
Data columns (total 6 columns):
 #   Column                                                                Non-Null Count   Dtype
---  ------                                                                --------------   -----
 0   station_abbr                                                          361674 non-null  object
 1   reference_timestamp                                                   361674 non-null  datetime64[ns]
 2   Température de l'air à 2 m du sol/ moyenne journalière                320334 non-null  float64
 3   Vitesse du vent scalaire/ moyenne journalière en m/s                  312995 non-null  float64
 4   Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant       353343 non-null  float64
 5   Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC  43547 non-null   float64
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 19.3+ MB

,station_abbr,reference_timestamp,Température de l'air à 2 m du sol/ moyenne journalière,Vitesse du vent scalaire/ moyenne journalière en m/s,Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant,Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC
21914,Arosa,1960-01-01,0.5,0.4,0.0,NaN
21915,Arosa,1960-01-02,-1.5,1.4,3.2,NaN
21916,Arosa,1960-01-03,-0.9,0.0,9.8,NaN
21917,Arosa,1960-01-04,-3.9,0.0,0.0,NaN
21918,Arosa,1960-01-05,-1.3,0.0,5.2,NaN

Nombre de donnée manquante dans la base

In [79]:
dataWeather_1500_2000_name.isnull().sum(axis=0)

station_abbr                                                                 0
reference_timestamp                                                          0
Température de l'air à 2 m du sol/ moyenne journalière                   41340
Vitesse du vent scalaire/ moyenne journalière en m/s                     48679
Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant           8331
Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC    318127
dtype: int64

Information sur la base de donnée 2000 mètres à 2500 mètres

In [80]:
dataWeather_2000_2500_name.info()
dataWeather_2000_2500_name.head()

<class 'pandas.core.frame.DataFrame'>
Index: 121463 entries, 18392 to 177108
Data columns (total 6 columns):
 #   Column                                                                Non-Null Count   Dtype
---  ------                                                                --------------   -----
 0   station_abbr                                                          121463 non-null  object
 1   reference_timestamp                                                   121463 non-null  datetime64[ns]
 2   Température de l'air à 2 m du sol/ moyenne journalière                116623 non-null  float64
 3   Vitesse du vent scalaire/ moyenne journalière en m/s                  106780 non-null  float64
 4   Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant       86736 non-null   float64
 5   Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC  5632 non-null    float64
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 6.5+ MB

,station_abbr,reference_timestamp,Température de l'air à 2 m du sol/ moyenne journalière,Vitesse du vent scalaire/ moyenne journalière en m/s,Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant,Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC
18392,Passo del Bernina,1960-01-01,NaN,NaN,0.0,NaN
18393,Passo del Bernina,1960-01-02,NaN,NaN,4.5,NaN
18394,Passo del Bernina,1960-01-03,NaN,NaN,1.3,NaN
18395,Passo del Bernina,1960-01-04,NaN,NaN,0.0,NaN
18396,Passo del Bernina,1960-01-05,NaN,NaN,0.0,NaN

Nombre de donnée manquante dans la base

In [81]:
dataWeather_2000_2500_name.isnull().sum(axis=0)

station_abbr                                                                 0
reference_timestamp                                                          0
Température de l'air à 2 m du sol/ moyenne journalière                    4840
Vitesse du vent scalaire/ moyenne journalière en m/s                     14683
Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant          34727
Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC    115831
dtype: int64

Information sur la base de donnée 2500 mètres à 3000 mètres

In [82]:
dataWeather_2500_3000_name.info()
dataWeather_2500_3000_name.head()

<class 'pandas.core.frame.DataFrame'>
Index: 91540 entries, 0 to 120149
Data columns (total 6 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   station_abbr                                                          91540 non-null  object
 1   reference_timestamp                                                   91540 non-null  datetime64[ns]
 2   Température de l'air à 2 m du sol/ moyenne journalière                90573 non-null  float64
 3   Vitesse du vent scalaire/ moyenne journalière en m/s                  91109 non-null  float64
 4   Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant       52089 non-null  float64
 5   Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC  0 non-null      float64
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 4.9+ MB

,station_abbr,reference_timestamp,Température de l'air à 2 m du sol/ moyenne journalière,Vitesse du vent scalaire/ moyenne journalière en m/s,Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant,Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC
0,Les Attelas,1993-08-11,6.7,2.6,NaN,NaN
1,Les Attelas,1993-08-12,9.4,3.6,NaN,NaN
2,Les Attelas,1993-08-13,9.2,2.4,NaN,NaN
3,Les Attelas,1993-08-14,9.2,3.0,NaN,NaN
4,Les Attelas,1993-08-15,7.9,2.8,NaN,NaN

Nombre de donnée manquante dans la base

In [83]:
dataWeather_2500_3000_name.isnull().sum(axis=0)

station_abbr                                                                0
reference_timestamp                                                         0
Température de l'air à 2 m du sol/ moyenne journalière                    967
Vitesse du vent scalaire/ moyenne journalière en m/s                      431
Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant         39451
Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC    91540
dtype: int64

Information sur la base de donnée 3000 mètres à 3500 mètres

In [84]:
dataWeather_3000_3500_name.info()
dataWeather_3000_3500_name.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39297 entries, 0 to 39296
Data columns (total 6 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   station_abbr                                                          39297 non-null  object
 1   reference_timestamp                                                   39297 non-null  datetime64[ns]
 2   Température de l'air à 2 m du sol/ moyenne journalière                38936 non-null  float64
 3   Vitesse du vent scalaire/ moyenne journalière en m/s                  39022 non-null  float64
 4   Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant       17158 non-null  float64
 5   Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC  0 non-null      float64
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 1.8+ MB

,station_abbr,reference_timestamp,Température de l'air à 2 m du sol/ moyenne journalière,Vitesse du vent scalaire/ moyenne journalière en m/s,Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant,Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC
0,Piz Corvatsch,1979-07-27,1.5,NaN,NaN,NaN
1,Piz Corvatsch,1979-07-28,1.6,NaN,NaN,NaN
2,Piz Corvatsch,1979-07-29,3.9,NaN,NaN,NaN
3,Piz Corvatsch,1979-07-30,3.1,NaN,NaN,NaN
4,Piz Corvatsch,1979-07-31,1.7,NaN,NaN,NaN

Nombre de donnée manquante dans la base

In [85]:
dataWeather_3000_3500_name.isnull().sum(axis=0)

station_abbr                                                                0
reference_timestamp                                                         0
Température de l'air à 2 m du sol/ moyenne journalière                    361
Vitesse du vent scalaire/ moyenne journalière en m/s                      275
Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant         22139
Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC    39297
dtype: int64

Information sur la base de donnée 3500 mètres à 4000 mètres

In [86]:
dataWeather_3500_4000_name.info()
dataWeather_3500_4000_name.head()

<class 'pandas.core.frame.DataFrame'>
Index: 23742 entries, 9861 to 33602
Data columns (total 6 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   station_abbr                                                          23742 non-null  object
 1   reference_timestamp                                                   23742 non-null  datetime64[ns]
 2   Température de l'air à 2 m du sol/ moyenne journalière                23742 non-null  float64
 3   Vitesse du vent scalaire/ moyenne journalière en m/s                  23455 non-null  float64
 4   Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant       0 non-null      float64
 5   Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC  0 non-null      float64
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 1.3+ MB

,station_abbr,reference_timestamp,Température de l'air à 2 m du sol/ moyenne journalière,Vitesse du vent scalaire/ moyenne journalière en m/s,Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant,Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC
9861,Jungfraujoch,1960-01-01,-9.9,14.2,NaN,NaN
9862,Jungfraujoch,1960-01-02,-9.9,10.5,NaN,NaN
9863,Jungfraujoch,1960-01-03,-12.1,19.0,NaN,NaN
9864,Jungfraujoch,1960-01-04,-10.5,12.3,NaN,NaN
9865,Jungfraujoch,1960-01-05,-7.1,6.7,NaN,NaN

Nombre de donnée manquante dans la base

In [87]:
dataWeather_3500_4000_name.isnull().sum(axis=0)

station_abbr                                                                0
reference_timestamp                                                         0
Température de l'air à 2 m du sol/ moyenne journalière                      0
Vitesse du vent scalaire/ moyenne journalière en m/s                      287
Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant         23742
Hauteur de neige (mesurée automatiquement)/ mesure matinale de 6 UTC    23742
dtype: int64