# Statistic
Source of the data (Quelle: MeteoSchweiz; Source: MétéoSuisse; Fonte: MeteoSvizzera; Source: MeteoSwiss)

In [1]:
import pandas as pd

import matplotlib.pyplot as plt

import os
from datetime import datetime

Function assemble les données et les enregistre

In [2]:
df_list = []
current_directory = os.getcwd()

OUTPUT_CSV = "\\data\\dataWeather.csv"

folder_path = current_directory + "\\data\\dataTemp\\month"
csv_files = os.listdir(folder_path)

pathFile = 'data/dataWeather.csv'
if not os.path.isfile(pathFile):
    for file in csv_files:
        try:
            file_path = folder_path + '\\' + file
            # Get the file size in kbytes
            file_size = os.path.getsize(file_path) / 1024

            if file_size > 1000:
                df = pd.read_csv(folder_path + '\\' + file)
                df_list.append(df)

        except Exception as e:
            print(f"⚠️ Erreur de lecture {file} : {e}")

    # Concaténation avec gestion des colonnes manquantes
    if df_list:
        df_final = pd.concat(df_list, ignore_index=True, sort=False)
        df_final.to_csv(current_directory + OUTPUT_CSV, index=False)
        print(f"✅ Fichier final enregistré sous {OUTPUT_CSV}")

Ouvre le fichier de donnée sur les satations

In [3]:
dataWeather =  pd.read_csv('data/dataWeather.csv', sep=';')

print(f"Dimension des données: {dataWeather.shape}")

Dimension des données: (4645786, 37)

Ouverture du fichier pour la corespondance des noms de colonne

In [4]:
columns_identifier = pd.read_csv('data/columns_identifier.csv', sep=';', encoding="latin1")

columns_identifier.head()

,parameter_shortname,parameter_description_de,parameter_description_fr,parameter_description_it,parameter_description_en,parameter_group_de,parameter_group_fr,parameter_group_it,parameter_group_en,parameter_granularity,parameter_decimals,parameter_datatype,parameter_unit
0,dkl010d0,Windrichtung; Tagesmittel,Direction du vent; moyenne journalière,Direzione del vento; media giornaliera,Wind direction; daily mean,Wind,vent,vento,wind,D,0,Integer,°
1,dkl010h0,Windrichtung; Stundenmittel,Direction du vent; moyenne horaire,Direzione del vento; media oraria,Wind direction; hourly mean,Wind,vent,vento,wind,H,0,Integer,°
2,dkl010z0,Windrichtung; Zehnminutenmittel,Direction du vent; moyenne sur 10 minutes,Direzione del vento; media su 10',Wind direction; ten minutes mean,Wind,vent,vento,wind,T,0,Integer,°
3,erefaod0,Referenzverdunstung nach FAO; Tagessumme,Évaporation de réference de FAO; somme journal...,Evaporazione referenze di FAO; somma giornaliera,Reference evaporation from FAO; daily total,Verdunstung,évaporation,evaporazione,evaporation,D,1,Float,mm/d
4,erefaoh0,Referenzverdunstung nach FAO; Stundensumme,Évaporation de réference de FAO; somme horaire,Evaporazione referenze di FAO; somma oraria,Reference evaporation from FAO; hourly total,Verdunstung,évaporation,evaporazione,evaporation,H,3,Float,mm/h

Ouverture du fichier d'itentification des stations

In [5]:
station_identifier = pd.read_csv('data/station_identifier.csv', sep=';', encoding="latin1")

station_identifier.head()

,station_abbr,station_name,station_canton,station_wigos_id,station_type_de,station_type_fr,station_type_it,station_type_en,station_dataowner,station_data_since,...,station_coordinates_wgs84_lat,station_coordinates_wgs84_lon,station_exposition_de,station_exposition_fr,station_exposition_it,station_exposition_en,station_url_de,station_url_fr,station_url_it,station_url_en
0,ABO,Adelboden,BE,0-20000-0-06735,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,"MeteoSchweiz, SLF",01.01.1901,...,46.491703,7.560703,Südosthang,Versant sud-est,Versante sud-orientale,south-eastern oriented slope,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
1,AEG,Oberägeri,ZG,0-20000-0-06676,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.02.1993,...,47.133636,8.608206,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
2,AIG,Aigle,VD,0-20000-0-06712,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.01.1961,...,46.326647,6.924472,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
3,ALT,Altdorf,UR,0-20000-0-06672,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.01.1864,...,46.887069,8.621894,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...
4,AND,Andeer,GR,0-20000-0-06787,Automatische Wetterstationen,Stations météorologiques automatiques,Stazioni meteorologiche automatiche,Automatic weather stations,MeteoSchweiz,01.01.1901,...,46.610139,9.431981,Ebene,Plaine,Pianura,plain,https://www.meteoschweiz.admin.ch/service-und-...,https://www.meteosuisse.admin.ch/services-et-p...,https://www.meteosvizzera.admin.ch/servizi-e-p...,https://www.meteoswiss.admin.ch/services-and-p...

####   Column selectionnée                                                                               

 <div style="vertical-align: middle;">
    <p>station_abbr</p>
    <p>station_height_masl</p>
    <p>reference_timestamp</p>
    <p>Température de l'air à 2 m du sol/ moyenne journalière [tre200d0]</p>
    <p>Vitesse du vent scalaire/ moyenne journalière en m/s  [fkl010d0]</p>
    <p>Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant [rre150d0]</p>
    <p>Hauteur de neige (mesurée automatiquement) / mesure matinale de 6 UTC [htoautd0]</p>
    <p>Durée d'ensoleillement/ relativement à la somme journalière maximale possible [sremaxdv]</p>
</div>

In [6]:
columns_list = ['station_abbr','reference_timestamp','tre200d0','fkl010d0','rre150d0', 'htoautd0', 'sremaxdv']

complete_list = list(columns_identifier['parameter_shortname'])

column_names = dataWeather.columns.tolist()

dif_list = list(set(column_names) ^ set(columns_list))

dataWeather_select = dataWeather.drop(columns=dif_list, axis=1)

dataWeather_select.head()

,station_abbr,reference_timestamp,tre200d0,fkl010d0,rre150d0,htoautd0,sremaxdv
0,ABO,01.01.1901 00:00,NaN,NaN,0.6,NaN,NaN
1,ABO,02.01.1901 00:00,NaN,NaN,1.8,NaN,NaN
2,ABO,03.01.1901 00:00,NaN,NaN,0.2,NaN,NaN
3,ABO,04.01.1901 00:00,NaN,NaN,0.0,NaN,NaN
4,ABO,05.01.1901 00:00,NaN,NaN,0.0,NaN,NaN

Change le format de la date et ajoute une cologne mois et année

In [7]:
dataWeather_select['reference_timestamp'] = pd.to_datetime(dataWeather_select['reference_timestamp'], format='%d.%m.%Y %H:%M')
dataWeather_select['year'] = dataWeather_select['reference_timestamp'].dt.year
dataWeather_select['month'] = dataWeather_select['reference_timestamp'].dt.month
dataWeather_select.head()

,station_abbr,reference_timestamp,tre200d0,fkl010d0,rre150d0,htoautd0,sremaxdv,year,month
0,ABO,1901-01-01,NaN,NaN,0.6,NaN,NaN,1901,1
1,ABO,1901-01-02,NaN,NaN,1.8,NaN,NaN,1901,1
2,ABO,1901-01-03,NaN,NaN,0.2,NaN,NaN,1901,1
3,ABO,1901-01-04,NaN,NaN,0.0,NaN,NaN,1901,1
4,ABO,1901-01-05,NaN,NaN,0.0,NaN,NaN,1901,1

Supprime les lignes en dessous de 1960

In [8]:
year_selected = 1960

dataWeather_select = dataWeather_select[dataWeather_select['reference_timestamp'].dt.year >= year_selected]
dataWeather_select.head()

,station_abbr,reference_timestamp,tre200d0,fkl010d0,rre150d0,htoautd0,sremaxdv,year,month
21458,ABO,1960-01-01,2.2,NaN,0.0,NaN,NaN,1960,1
21459,ABO,1960-01-02,1.5,NaN,15.2,NaN,NaN,1960,1
21460,ABO,1960-01-03,3.1,NaN,8.0,NaN,NaN,1960,1
21461,ABO,1960-01-04,0.1,NaN,0.0,NaN,NaN,1960,1
21462,ABO,1960-01-05,2.3,NaN,0.9,NaN,NaN,1960,1

Calcul la moyenne,  l'écart type, et le nombre d’observations

In [9]:
# Liste des colonnes numériques, sauf celles utilisées pour le groupby
columns_to_aggregate = dataWeather_select.select_dtypes(include='number').columns.difference(['station_abbr', 'year', 'month'])

# Agrégation multiple pour chaque colonne
dataWeather_msc = dataWeather_select.groupby(['station_abbr', 'year', 'month'])[columns_to_aggregate].agg(['mean', 'std', 'count']).reset_index()

# Aplatir les noms de colonnes pour plus de lisibilité
dataWeather_msc.columns = ['_'.join(col).strip('_') if isinstance(col, tuple) else col for col in dataWeather_msc.columns]

pd.set_option("display.max_columns", 114)

dataWeather_msc.shape
dataWeather_msc.head()

,station_abbr,year,month,fkl010d0_mean,fkl010d0_std,fkl010d0_count,htoautd0_mean,htoautd0_std,htoautd0_count,rre150d0_mean,rre150d0_std,rre150d0_count,sremaxdv_mean,sremaxdv_std,sremaxdv_count,tre200d0_mean,tre200d0_std,tre200d0_count
0,ABO,1960,1,NaN,NaN,0,NaN,NaN,0,2.200000,3.759876,31,NaN,NaN,0,-2.977419,6.304692,31
1,ABO,1960,2,NaN,NaN,0,NaN,NaN,0,3.344828,7.226518,29,NaN,NaN,0,0.265517,4.110377,29
2,ABO,1960,3,NaN,NaN,0,NaN,NaN,0,3.167742,6.800803,31,NaN,NaN,0,2.100000,2.266716,31
3,ABO,1960,4,NaN,NaN,0,NaN,NaN,0,1.980000,3.196377,30,NaN,NaN,0,3.993333,3.087900,30
4,ABO,1960,5,NaN,NaN,0,NaN,NaN,0,3.222581,5.937492,31,NaN,NaN,0,10.029032,3.071720,31

Fait la moyenne par mois

In [10]:
# 1. Identifie les colonnes
mean_cols = [col for col in dataWeather_msc.columns if col.endswith('_mean')]
std_cols = [col.replace('_mean', '_std') for col in mean_cols]
count_cols = [col.replace('_mean', '_count') for col in mean_cols]

# 2. Grouper par station + mois
grouped_means = dataWeather_msc.groupby(['station_abbr', 'month'])[mean_cols].mean()
grouped_stds = dataWeather_msc.groupby(['station_abbr', 'month'])[std_cols].mean()
grouped_counts = dataWeather_msc.groupby(['station_abbr', 'month'])[count_cols].sum()

# 3. Fusionner les trois sous-tables
dataWeather_month = pd.concat([grouped_means, grouped_stds, grouped_counts], axis=1).reset_index()

# Affichage
dataWeather_month.head()

,station_abbr,month,fkl010d0_mean,htoautd0_mean,rre150d0_mean,sremaxdv_mean,tre200d0_mean,fkl010d0_std,htoautd0_std,rre150d0_std,sremaxdv_std,tre200d0_std,fkl010d0_count,htoautd0_count,rre150d0_count,sremaxdv_count,tre200d0_count
0,ABO,1,1.390979,16.542316,2.900447,46.505562,-1.577965,1.188149,9.576727,5.182609,40.312733,4.056368,1829,458,2015,1798,2015
1,ABO,2,1.495592,22.026638,2.940983,48.361368,-1.106175,1.075535,7.529787,5.557565,40.184200,3.849922,1667,414,1837,1639,1837
2,ABO,3,1.612411,8.586499,2.982084,46.932703,1.355087,1.056990,11.860402,5.173191,38.504304,3.823292,1829,458,2015,1798,2015
3,ABO,4,1.619605,0.590868,3.062410,43.836207,4.492051,0.776551,3.361567,5.162913,35.665133,3.896143,1770,440,1950,1740,1950
4,ABO,5,1.591799,-0.028796,4.036725,40.978309,8.781290,0.650226,0.880330,6.379034,33.371711,3.543397,1829,448,2015,1798,2015

Fait  la moyenne par année

In [11]:
# Regroupe par station et calcule la moyenne annuelle de chaque variable
dataWeather_year = dataWeather_month.groupby('station_abbr', as_index=False).mean(numeric_only=True)
# Affichage
dataWeather_year.head()

,station_abbr,month,fkl010d0_mean,htoautd0_mean,rre150d0_mean,sremaxdv_mean,tre200d0_mean,fkl010d0_std,htoautd0_std,rre150d0_std,sremaxdv_std,tre200d0_std,fkl010d0_count,htoautd0_count,rre150d0_count,sremaxdv_count,tre200d0_count
0,ABO,6.5,1.474745,5.015566,3.630240,47.724045,5.996213,0.848481,4.172658,6.356452,36.669211,3.657436,1795.583333,448.666667,1978.500000,1778.083333,1978.500000
1,AIG,6.5,1.962928,0.073073,2.732171,50.670068,10.362599,0.803231,0.124120,5.392613,36.469206,2.781095,1334.083333,61.166667,1339.250000,1339.250000,1339.250000
2,ALT,6.5,2.357943,0.013620,3.232982,43.867026,9.865347,1.925657,0.081495,6.094402,36.947317,3.254316,1978.500000,32.583333,1978.416667,1978.500000,1978.500000
3,AND,6.5,1.436263,NaN,2.631831,52.517336,7.699566,0.818204,NaN,6.054165,37.084554,3.137233,506.333333,0.000000,1978.500000,506.333333,506.333333
4,ANT,6.5,2.453886,NaN,3.794677,49.961684,3.964073,1.196134,NaN,7.431556,37.369926,3.492500,1446.416667,0.000000,1978.500000,338.416667,1978.500000

# Graphique
### Recap sur les Colonne                                                                               

 <div style="vertical-align: middle;">
    <p style="color:MediumSeaGreen;">station_abbr</p>
    <p style="color:MediumSeaGreen;">station_name</p>
    <p style="color:MediumSeaGreen;">year</p>
    <p style="color:MediumSeaGreen;">month</p>
    <p style="color:MediumSeaGreen;">station_height_masl</p>
    <p style="color:MediumSeaGreen;">reference_timestamp</p>
    <p style="color:MediumSeaGreen;">station_coordinates_wgs84_lat</p>
    <P style="color:MediumSeaGreen;">station_coordinates_wgs84_lon</P>
    <p>Température de l'air à 2 m du sol/ moyenne journalière</p>
    <p style="color:MediumSeaGreen;">Variable ==> base: [tre200d0]; moyenne: [tre200d0_mean]; 
    écart type: [tre200d0_std]; nombre de valeur[tre200d0_count]</p>
    <p>Vitesse du vent scalaire/ moyenne journalière en m/s</p>
    <p style="color:MediumSeaGreen;">Variable ==> base: [fkl010d0]; moyenne: [fkl010d0_mean]; 
    écart type: [fkl010d0_std]; nombre de valeur[fkl010d0_count]</p>
    <p>PPrécipitations/ somme journalière 6 UTC - 6 UTC du jour suivant</p>
    <p style="color:MediumSeaGreen;">Variable ==> base: [rre150d0]; moyenne: [rre150d0_mean]; 
    écart type: [rre150d0_std]; nombre de valeur[rre150d0_count]</p>
    <p>Hauteur de neige (mesurée automatiquement) / mesure matinale de 6 UTC</p>
    <p style="color:MediumSeaGreen;">Variable ==> base: [htoautd0]; moyenne: [htoautd0_mean]; 
    écart type: [htoautd0_std]; nombre de valeur[htoautd0_count]</p>
    <p>Durée d'ensoleillement/ relativement à la somme journalière maximale possible</p>
    <p style="color:MediumSeaGreen;">Variable ==> base: [sremaxdv]; moyenne: [sremaxdv_mean]; 
    écart type: [sremaxdv_std]; nombre de valeur[sremaxdv_count]</p>
</div>

In [12]:
import folium
from IPython.display import display, clear_output
from ipywidgets import widgets
import matplotlib.cm as cm
import matplotlib.colors as colors
from matplotlib.pylab import norm
import numpy as np
from folium import Popup
from branca.element import IFrame

In [13]:
# Return l'unité de la ligne
def value_unit(param_id):
    result = columns_identifier.loc[
        columns_identifier['parameter_shortname'] == param_id, 'parameter_unit'
    ]

    return result.values[0] if not result.empty else None

# Return la définiton du la colonne en fonction de son id
def columnDefinition(param_id, language='fr'):
    lang_map = {
        'fr': 'parameter_description_fr',
        'en': 'parameter_description_en',
        'de': 'parameter_description_de',
        'it': 'parameter_description_it'
    }
    col = lang_map.get(language, 'parameter_description_en')

    result = columns_identifier.loc[
        columns_identifier['parameter_shortname'] == param_id, col
    ]

    return result.values[0] if not result.empty else None


# Return l'id en fonction de la définiton du la colonne
def columnId(description, language='fr'):
    lang_map = {
        'fr': 'parameter_description_fr',
        'en': 'parameter_description_en',
        'de': 'parameter_description_de',
        'it': 'parameter_description_it'
    }
    col = lang_map.get(language, 'parameter_description_en')

    matches = columns_identifier[
        columns_identifier[col].str.contains(description, case=False, na=False, regex=False)
    ]

    if matches.empty:
        return None  # Ou renvoyer un message

    return matches.iloc[0]['parameter_shortname']

In [14]:
months_labels = [
    ("Janvier", 1), ("Février", 2), ("Mars", 3), ("Avril", 4),
    ("Mai", 5), ("Juin", 6), ("Juillet", 7), ("Août", 8),
    ("Septembre", 9), ("Octobre", 10), ("Novembre", 11), ("Décembre", 12)
]

colormaps_personnalisees = {
    'tre200d0': 'coolwarm',     # Température de l'air à 2 m du sol/ moyenne journalière
    'sremaxdv': 'YlOrBr',       # Durée d'ensoleillement/ relativement à la somme journalière maximale possible
    'rre150d0': 'PuBuGn',       # Précipitations/ somme journalière 6 UTC - 6 UTC du jour suivant
    'htoautd0': 'Oranges',      # Hauteur de neige (mesurée automatiquement) / mesure matinale de 6 UTC
    'fkl010d0': 'Greys'         # Vitesse du vent scalaire/ moyenne journalière en m/s 
    # ajoute d'autres associations ici si besoin
}

language = 'fr'

#création des widgets
slider_altitude = widgets.IntRangeSlider(value = [400, 4000], min=400, max=4000, step=50, description='Altitude ≥', continous_update = False)
dropdown = widgets.Dropdown(options=months_labels, value=1, description='Mois :')
colorbar_checkbox = widgets.Checkbox(value=False, description='Display colorbar', disabled=False)

variable_available = [columnDefinition(col.replace('_mean', ''), language)  for col in dataWeather_year.columns if col.endswith('_mean')]

data_selection = widgets.Dropdown(options=variable_available, description="Variable :")


def update_map(altitude_range, data_selection, month, colorbar_checkbox):

    month_name = months_labels[month - 1][0]

    alt_min, alt_max = altitude_range

    df_month = dataWeather_month[dataWeather_month['month'] == month].copy()
    
    if df_month.empty:
        print("Aucune donnée pour ce mois.")
        return
    
    data_id = columnId(data_selection, language)

    val_mean = f"{data_id}_mean"
    val_count = f"{data_id}_count"
    #val_std = f"{data_selection}_std"

    # Récupère l’unité
    try:
        unit = columns_identifier.loc[
            columns_identifier['parameter_shortname'] == data_id, 'parameter_unit'
        ].values[0]
    except IndexError:
        unit = ""  # Valeur vide si non trouvée


    # Choix de la color map dynamique
    cmap_name = colormaps_personnalisees.get(data_id, 'viridis')
    cmap = plt.get_cmap(cmap_name)

    # Normalisation pour la couleur
    norm = colors.Normalize(vmin=df_month[val_mean].min(), vmax=df_month[val_mean].max())

    folium_map = folium.Map(location=[46.8, 8.3], zoom_start=8, width='80%', height='80%')
    popup = folium.Popup("Contenu du popup", max_width=800)


    # Génération des marqueurs
    for _, station in station_identifier.iterrows():
        if not alt_min <= station['station_height_masl'] <= alt_max:
            continue

        station_abbr = station['station_abbr']
        row = df_month[df_month['station_abbr'] == station_abbr]

        if row.empty:
            continue

        value = row.iloc[0][val_mean]
        count = row.iloc[0].get(val_count, 1)
        
        if count < 300 or pd.isna(value):
            continue  # Ignore cette station si données insuffisantes


        radius = max(4, min(8, np.sqrt(count)))
        color = colors.to_hex(cmap(norm(value)))

        # 🧾 Popup stylisé
        html_popup = f"""
        <div style='font-family: Arial; font-size: 13px;'>
            <b style='font-size: 15px;'>{station['station_name']}</b><br>
            🏔️ Altitude : {station['station_height_masl']} m<br>
            📈 Valeur : {value:.2f} {unit}<br>
            📊 Observation{'s' if count > 1 else ''} : {count}
        </div>
        """
        iframe = IFrame(html=html_popup, width=200, height=100)
        popup = Popup(iframe, max_width=200)

        folium.CircleMarker(
            location=[
                station['station_coordinates_wgs84_lat'],
                station['station_coordinates_wgs84_lon']
            ],
            radius=radius,
            color=color,
            fill=True,
            fill_opacity=0.8,
            popup=popup
        ).add_to(folium_map)

    # Générer une légende simple
    if colorbar_checkbox:
        vmin = df_month[val_mean].min()
        vmax = df_month[val_mean].max()
        vavg = df_month[val_mean].mean()
        legend_html = f"""
        <div style="
            position: fixed;
            bottom: 50px;
            left: 50px;
            width: 450px;
            height: 150px;
            background-color: white;
            border:2px solid grey;
            z-index:9999;
            font-size:14px;
            padding: 10px;
        ">
        <b>{data_selection} pour le mois {month_name}</b><br><br>
        <i style="background:#3b4cc0;color:#3b4cc0">•••</i> Valeur min : {vmin:.1f} {unit}<br>
        <i style="background:#fdae61;color:#fdae61">•••</i> Moyenne : {vavg:.1f} {unit}<br>
        <i style="background:#d7191c;color:#d7191c">•••</i> Valeur max : {vmax:.1f} {unit}<br>
        </div>
        """
        folium_map.get_root().html.add_child(folium.Element(legend_html))

    display(folium_map)

widgets.interact(update_map, altitude_range=slider_altitude, data_selection=data_selection, month=dropdown, colorbar_checkbox=colorbar_checkbox)

interactive(children=(IntRangeSlider(value=(400, 4000), description='Altitude ≥', max=4000, min=400, step=50),…

Calcul d'une note par station, colonne et par mois, et la moyenne par mois

In [15]:
# Étape 1 : Sélection des colonnes _mean (sauf htoautd0)
mean_cols = [
    col for col in dataWeather_month.columns
    if col.endswith('_mean') and col != 'htoautd0_mean'
]

# Étape 2 : Création du DataFrame des scores
scores_df = dataWeather_month[['station_abbr', 'month']].copy()

# Étape 3 : Génération des scores de 0 à 10
for col in mean_cols:
    col_min = dataWeather_month[col].min()
    col_max = dataWeather_month[col].max()
    score_col = col.replace('_mean', '_score')

    if col in ['rre150d0_mean', 'fkl010d0_mean']:
        # Inversion : moins = mieux
        scores_df[score_col] = (1 - (dataWeather_month[col] - col_min) / (col_max - col_min)) * 10
    else:
        # Standard : plus = mieux
        scores_df[score_col] = ((dataWeather_month[col] - col_min) / (col_max - col_min)) * 10
    

scores_df = scores_df.round(1)


# Liste des colonnes de score à inclure
score_cols = [col for col in scores_df.columns if col.endswith('_score')]

# Moyenne des scores
scores_df['overall_rating'] = scores_df[score_cols].mean(axis=1).round(1)

# Supprimer les lignes incomplètes
scores_df = scores_df.dropna(subset=score_cols + ['overall_rating']).round(1)

# 
scores_df = scores_df.sort_values(by=['month', 'overall_rating'], ascending=[True, False])

scores_df.groupby('month').first()[['station_abbr',  'overall_rating']]

display(scores_df)

,station_abbr,month,fkl010d0_score,rre150d0_score,sremaxdv_score,tre200d0_score,overall_rating
792,GRO,1,9.9,8.9,7.1,4.3,7.6
1668,VIO,1,7.9,8.8,10.0,3.6,7.6
420,COM,1,9.1,9.1,7.2,4.2,7.4
1236,OTL,1,9.5,8.6,6.8,4.7,7.4
144,BIA,1,8.3,8.5,7.8,4.7,7.3
...,...,...,...,...,...,...,...
1619,TIT,12,2.3,8.6,4.6,1.4,4.2
815,GSB,12,5.2,4.5,4.7,2.1,4.1
335,CHA,12,0.0,7.2,3.2,3.4,3.4
527,DOL,12,1.0,4.8,3.7,3.3,3.2
1415,SAE,12,2.4,3.8,4.3,2.0,3.1

tableau des score par station, mois

In [16]:
scores_month = scores_df[['station_abbr', 'month', 'overall_rating']].copy()

scores_month = scores_month.merge(
    station_identifier[['station_abbr', 'station_name']], 
    on='station_abbr', 
    how='left'  # ou 'inner' si tu veux ignorer les stations non communes
)


display(scores_month)

     station_abbr  month  overall_rating              station_name
0             GRO      1             7.6                     Grono
1             VIO      1             7.6               Vicosoprano
2             COM      1             7.4  Acquarossa / Comprovasco
3             OTL      1             7.4           Locarno / Monti
4             BIA      1             7.3                    Biasca
...           ...    ...             ...                       ...
1411          TIT     12             4.2                    Titlis
1412          GSB     12             4.1   Col du Grand St-Bernard
1413          CHA     12             3.4                 Chasseral
1414          DOL     12             3.2                   La Dôle
1415          SAE     12             3.1                    Säntis

[1416 rows x 4 columns]

tableau des score par station, année

In [17]:
scores_annuel = (
    scores_month
    .groupby('station_abbr', as_index=False)['overall_rating']
    .mean()
    .round(1)
    .sort_values(by='overall_rating', ascending=False)
)

display(scores_annuel)

    station_abbr  overall_rating
86           PSI             8.2
101          SIO             7.8
51           GRO             7.6
48           GRC             7.5
118          ZER             7.5
..           ...             ...
82           PIL             4.9
33           DOL             4.6
22           CHA             4.6
93           SAE             4.1
107          TIT             3.8

[119 rows x 2 columns]

Crée un tableau pour le top 10 des stations par mois

In [18]:
# Liste pour stocker les top 10 de chaque mois
top10_month = []

# Boucle sur les 12 mois
for month in range(1, 13):
    scores_month = scores_df[scores_df['month'] == month]
    top10 = scores_month.sort_values(by='overall_rating', ascending=False).head(10)
    top10_month.append(top10)

# Concaténation en un seul DataFrame
top10_station_month = pd.concat(top10_month).reset_index(drop=True)

# Réorganisation des colonnes
top10_station_month = top10_station_month[['station_abbr', 'month', 'overall_rating']]

top10_station_month = top10_station_month.merge(
    station_identifier[['station_abbr', 'station_name']], 
    on='station_abbr', 
    how='left'  # ou 'inner' si tu veux ignorer les stations non communes
)

display(top10_station_month)

    station_abbr  month  overall_rating              station_name
0            GRO      1             7.6                     Grono
1            VIO      1             7.6               Vicosoprano
2            COM      1             7.4  Acquarossa / Comprovasco
3            OTL      1             7.4           Locarno / Monti
4            BIA      1             7.3                    Biasca
..           ...    ...             ...                       ...
115          GRC     12             7.1                   Grächen
116          LUG     12             7.1                    Lugano
117          AND     12             7.0                    Andeer
118          EVO     12             7.0           Evolène / Villa
119          LAT     12             7.0           Bergün / Latsch

[120 rows x 4 columns]

Crée un tableau pour le top 10 des stations par année

In [19]:
top10_stations_year = scores_annuel.head(10).reset_index(drop=True)

top10_stations_year = top10_stations_year.merge(
    station_identifier[['station_abbr', 'station_name']], 
    on='station_abbr', 
    how='left'  # ou 'inner' si tu veux ignorer les stations non communes
)

display(top10_stations_year)

  station_abbr  overall_rating       station_name
0          PSI             8.2  Würenlingen / PSI
1          SIO             7.8               Sion
2          GRO             7.6              Grono
3          GRC             7.5            Grächen
4          ZER             7.5            Zermatt
5          EVO             7.4    Evolène / Villa
6          AND             7.4             Andeer
7          VIS             7.4               Visp
8          MTE             7.3             Mottec
9          LAT             7.3    Bergün / Latsch

In [20]:
import seaborn as sns
import matplotlib.pyplot as plt

In [21]:
def configurerStyleGraphic():
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        'font.family': 'Segoe UI Emoji',     # Pour les emojis 🏔️☀️📅
        'axes.titlesize': 14,
        'axes.labelsize': 12,
        'xtick.labelsize': 10,
        'ytick.labelsize': 10,
        'figure.facecolor': 'white',
        'axes.edgecolor': 'gray',
        'axes.grid': True,
        'grid.alpha': 0.3,
        'grid.linestyle': '--',
    })

In [22]:
selection_mode = widgets.Dropdown(
    options=["Classement annuel", "Top 10 par mois"],
    description="Affichage :"
)

selection_month = widgets.Dropdown(
    options=[(month, num) for (month, num) in months_labels],
    value=1,
    description='Mois :'
)

def updateVisibilityMnth(mode):
    if mode == "Classement annuel":
        selection_month.layout.display = 'none'
    else:
        selection_month.layout.display = ''

selection_mode.observe(lambda change: updateVisibilityMnth(change['new']), names='value')
updateVisibilityMnth(selection_mode.value)


def displayTop10(mode, month):
    plt.figure(figsize=(10, 6))
    configurerStyleGraphic()
    
    if mode == "Classement annuel":
        plt.barh(top10_stations_year['station_name'], top10_stations_year['overall_rating'], color='mediumseagreen')
        plt.xlabel("Note annuelle moyenne")
        plt.title("🏆 Top 10 des stations sur l’année")
        plt.gca().invert_yaxis()
        plt.grid(axis='x', linestyle='--', alpha=0.4)
        plt.tight_layout()
        
        plt.rcParams['font.family'] = 'Segoe UI Emoji'

        plt.show()

    elif mode == "Top 10 par mois":
        top10_month = (
            top10_station_month[top10_station_month['month'] == month]
            .sort_values(by='overall_rating', ascending=False)
            .head(10)
        )

        plt.barh(top10_month['station_name'], top10_month['overall_rating'], color='cornflowerblue')
        month_name = months_labels[month - 1][0]
        plt.xlabel("Note mensuelle")
        plt.title(f"📅 Top 10 des stations en {month_name}")
        plt.gca().invert_yaxis()
        plt.grid(axis='x', linestyle='--', alpha=0.4)
        plt.tight_layout()
        plt.rcParams['font.family'] = 'Segoe UI Emoji'

        plt.show()

widgets.interact(
    displayTop10,
    mode=selection_mode,
    month=selection_month
)

interactive(children=(Dropdown(description='Affichage :', options=('Classement annuel', 'Top 10 par mois'), va…

In [23]:
import folium
from folium.plugins import MarkerCluster

def getTilesMonth(month):
    if month in [3, 4, 5]:     # Printemps
        return 'Stamen TonerLite'
    elif month in [6, 7, 8]:   # Été
        return 'CartoDB Positron'
    elif month in [9, 10, 11]: # Automne
        return 'Stamen Terrain'
    else:                      # Hiver
        return 'Stamen Toner'
    

selection_mode.observe(lambda change: updateVisibilityMnth(change['new']), names='value')
updateVisibilityMnth(selection_mode.value)

def displayMapTop10(mode, month):
    configurerStyleGraphic()
    
    # Choix des données selon le mode
    if mode == "Classement annuel":
        df = top10_stations_year
        df['month'] = 1  # valeur neutre
        month_title = "🏆 Carte : Top 10 des stations (note annuelle)"
        df_value = dataWeather_month.copy()
    else:
        df = top10_station_month[top10_station_month['month'] == month].sort_values(
            by='overall_rating', ascending=False).head(10).copy()
        month_title = f"📅 Carte : Top 10 des stations en {months_labels[month - 1][0]}"
        df_value = dataWeather_year.copy()

    tile = getTilesMonth(month if mode == "Top 10 par mois" else 1)

    attributions = {
        'CartoDB Positron': '© OpenStreetMap contributors, © CartoDB',
        'Stamen TonerLite': 'Map tiles by Stamen Design, CC BY 3.0 — Map data © OpenStreetMap',
        'Stamen Terrain': 'Map tiles by Stamen Design, CC BY 3.0 — Map data © OpenStreetMap',
        'Stamen Toner': 'Map tiles by Stamen Design, CC BY 3.0 — Map data © OpenStreetMap'
    }

    # Créer la carte centrée sur la Suisse
    folium_map = folium.Map(location=[46.8, 8.3], zoom_start=8, width='80%', height='80%')
    cluster = MarkerCluster().add_to(folium_map)

    def color_score(score):
        if score >= 8.5: return 'darkgreen'
        elif score >= 7: return 'orange'
        else: return 'red'

    # Ajout des marqueurs
    # Ajouter chaque station
    for _, station in station_identifier.iterrows():
        station_abbr = station['station_abbr']

        match = df[df['station_abbr'] == station_abbr]

        match_value = df_value[df_value['station_abbr'] == station_abbr]

        # Récupère l’unité
        try:
            unit_rainfall = columns_identifier.loc[
                columns_identifier['parameter_shortname'] == 'rre150d0', 'parameter_unit'
            ].values[0]
        except IndexError:
            unit_rainfall = ""  # Valeur vide si non trouvée

        try:
            unit_sunshine = columns_identifier.loc[
                columns_identifier['parameter_shortname'] == 'sremaxdv', 'parameter_unit'
            ].values[0]
        except IndexError:
            unit_sunshine = ""  # Valeur vide si non trouvée
        
        try:
            unit_snow_height = columns_identifier.loc[
                columns_identifier['parameter_shortname'] == 'htoautd0', 'parameter_unit'
            ].values[0]
        except IndexError:
            unit_snow_height = ""  # Valeur vide si non trouvée

    
        if not match.empty :
            note = match.iloc[0]['overall_rating']
            name = match.iloc[0]['station_name']
            rainfall = match_value.iloc[0]['rre150d0_mean']
            sunshine = match_value.iloc[0]['sremaxdv_mean']
            snow_height = match_value.iloc[0]['htoautd0_mean']
        
            lat = station['station_coordinates_wgs84_lat']
            lon = station['station_coordinates_wgs84_lon']
            score = note

            popup_html = f"""
            <b>{name}</b><br>
            ☀️ Ensoleillement : {sunshine:.1f} [{unit_sunshine}]<br>
            🌧️ Précipitations : {rainfall:.1f} [{unit_rainfall}]<br>
            ❄️ Neige : {snow_height:.1f} [{unit_snow_height}]<br>
            📈 Note : <b>{score}</b>
            """

            folium.CircleMarker(
                location=[lat, lon],
                radius=8,
                color=color_score(score),
                fill=True,
                fill_opacity=0.8,
                tooltip=folium.Tooltip(name),
                popup=folium.Popup(popup_html, max_width=250)
            ).add_to(cluster)

    display(folium_map)

widgets.interact(
    displayMapTop10,
    mode=selection_mode,
    month=selection_month
)

interactive(children=(Dropdown(description='Affichage :', options=('Classement annuel', 'Top 10 par mois'), va…